[".local/bin/imgcat"]
    type = "file"
    url = "https://iterm2.com/utilities/imgcat"
    executable = true

[".local/bin/iconset"]
    type = "file"
    url = "https://github.com/tale/iconset/releases/download/v1.0.0/iconset"
    executable = true
