[".local/bin/imgcat"]
    type = "file"
    url = "https://iterm2.com/utilities/imgcat"
    executable = true

[".local/bin/iconset"]
    type = "file"
    url = "https://github.com/tale/iconset/releases/download/v1.0.0/iconset"
    executable = true

[".local/scripts/add_to_dock"]
    type = "archive"
    url = "https://github.com/ryanpavlick/add_to_dock/archive/refs/heads/master.zip"
    stripComponents = 1

["Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package"]
    type = "file"
    url = "https://packagecontrol.io/Package%20Control.sublime-package"
