packages:
  brews:
    - ansifilter
    - bitwarden-cli
    - cmatrix
    - coreutils
    - duti
    - git
    - git-delta
    - grep
    - jenv
    - mas
    - nano
    - ncdu
    - poetry
    - ptpython
    - pygments
    - python
    - tlrc
    - tree
    - wget
    - yt-dlp
    - zsh-syntax-highlighting
    - zero-sh/tap/apply-user-defaults

  casks:
    # Apps
    - affinity-designer
    - affinity-photo
    - audacity
    - bitwarden
    - blender
    - discord
    - firefox
    - hex-fiend
    - iina
    - inkscape
    - intellij-idea-ce
    - iterm2
    - katrain
    - majsoul-plus
    - monodraw
    - obsidian
    - postman
    - slack
    - steam
    - sublime-text
    - visual-studio-code
    - whatsapp

    # Extensions
    - karabiner-elements
    - keepingyouawake
    - linearmouse
    - rectangle
    - switchresx
    - hiddenbar
    - topnotch
    # For dual GPU Macs (pre-M1)
    # - gfxcardstatus

  app_store:
    - "928941247"  # OTP Manager
    - "668208984"  # GIPHY Capture
    - "985367838"  # Outlook

  manual:
    - https://filezilla-project.org/download.php?platform=macos-arm64
    - https://www.image-line.com/fl-studio-download/

  setup:
    - /Applications/Rectangle.app
    - /Applications/Hidden Bar.app
    - /Applications/KeepingYouAwake.app
    - /Applications/LinearMouse.app
    - /Applications/TopNotch.app
    - ~/Library/PreferencePanes/SwitchResX.prefPaneSwitchResX
